### PR TITLE
General README cleanup and clarification

### PR DESCRIPTION
**Pull request by tylerdmace**

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
Two comments (independently of whether Evan will agree to such a big change to the README):
* Please don't remove the "[make sure it is going to give you these things](https://www.haskell.org/platform/contents.html)" link. It was there for a strong reason, as a reaction to several incidents in the past.
* When you now tell people to run `$ export PATH=$PATH:~/Elm-Platform/0.16/.cabal-sandbox/bin`, you are expecting (at least) that they are on some unixy OS. That might not be the case. The previous formulation was more vague (on purpose) and also included Windows people. Please revise.

**Comment by tylerdmace** [comment]
@jvoigtlaender Thank you for the feedback!  First, a revision for the HP installation requirements is incoming. Second, I don't see how I've ignored Windows any more than it already was.

Currently the README says:
> Now that you have chosen a home for Elm-Platform/, add the absolute path to Elm-Platform/0.16/.cabal-sandbox/bin to your PATH (like this). This is necessary to successfully build elm-reactor which relies on elm-make. This will also mean you can use elm commands from anywhere!

That's a very unix-dependent instruction, no? I do think that the README needs a lot more attention in regards to Windows build instructions but I don't think that this PR includes anything that has detracted from what was already there.

**Comment by jvoigtlaender** [comment]
> Second, I don't see how I've ignored Windows any more than it already was. ... That's a very unix-dependent instruction, no?

No, I don't think so. Hearing that they should add something to their `PATH` variable is something that Windows people can relate to. Windows does have a `PATH` variable, and Windows people can set that variable. But Windows doesn't have `export` or `~`, so the line `$ export PATH=$PATH:~/Elm-Platform/0.16/.cabal-sandbox/bin` will most likely look to Windows people as if it has nothing to do with them. So I do think the previous formulation was better.

**Comment by jvoigtlaender** [comment]
Another thing: I am convinced that any new README here should contain a pointer to the http://elm-lang.org/get-started page. See https://github.com/elm-lang/elm-platform/pull/84.

**Comment by jvoigtlaender** [comment]
And another random thought (:smile:): The first line of your README
> The [Elm Platform](http://elm-lang.org) bundles together a bunch of tools that make it nicer to use Elm, including

I don't think the Elm Platform is http://elm-lang.org. It is this repository.

And, when you say "nicer", I ask myself "nicer than what?". What are you comparing the Elm Platform to there?

**Comment by tylerdmace** [comment]
Let me address all these points real quick, in order:

* The current README says to update the PATH variable and then includes a link taking them to a Stackoverflow post where only *nix instructions are given.
* This is a fantastic idea.
* I'll update the link so the clickable text is only 'Elm' and will not include 'platform'.
* Current README uses the language, "... that make it nice to use Elm.". When I read this, I interpret this as "Elm is not nice to use unless we get these tools to go with it.". Obviously that's not true. Using Elm is a treat. The only thing these tools provide is a 'nicer' experience than that of one which doesn't include them. I was trying to choose language that would not make Elm seem like a poor experience by itself.

**Comment by jvoigtlaender** [comment]
Regarding the last point: "Elm is not nice to use unless we get these tools to go with it." Well, yes, actually it's impossible to use Elm unless we get these tools. Well, at least concerning `elm-compiler`, `elm-make`, and `elm-package`. But I really don't want to "fight" about this. What I'm really worried about is that I don't have much hope the work you are putting in here will actually have any impact on the README. :worried:

**Comment by tylerdmace** [comment]
Haha, fair enough! Thanks for letting me know :)

**Pull request closed without merging**
