### PR TITLE
Check GHC and cabal versions before attempting to build

### PR DESCRIPTION
**Pull request by jvoigtlaender**
I hope it's obvious why this is a good thing to do, but just in case, consider recent instances of what I've seen happening (and been dealing with in issues in this repository) again and again:
* https://groups.google.com/d/msg/elm-discuss/9657kue4zoE/FJVgH8TKBQAJ
* https://github.com/elm-lang/elm-platform/issues/30#issuecomment-173772272

What happens right now is that people run `BuildFromSource.hs`. The script downloads stuff, starts building, works a while, then fails. Then people don't know why that is. They have to go to the mailing list, or open an issue. Then it takes a human to look at the case, and after a while (maybe after some back and forth) to realize that it's just a too old compiler that was used. And tell the original person.

What should instead happen (and will happen with this pull request) is that `BuildFromSource.hs` tells the original person right away that they will need to upgrade GHC (and/or cabal). Then that person can act immediately, and everybody is saved work and time etc.

Who are the people with write access to this repository? @evancz, @rtfeldman? Please merge this quickly.

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
@evancz, please consider this before adding any 0.17 build route to the script, or announcing a 0.17-alpha or whatever. As soon as 0.17 is on the horizon, people will try to build it from source. With the foreseeable consequences as outlined in the above post.

**Comment by jvoigtlaender** [comment]
@evancz, @rtfeldman, I think you two are the only ones who can merge stuff in this repository. As such, I'd like to ask you to devote three minutes to reading the below:

It's happening again: https://github.com/elm-lang/elm-platform/issues/30#issuecomment-195947152. Someone tries to use `BuildFromSource.hs`, but it fails. It takes some volunteers' (in this case, @herberthamaral's and mine) time to find out what's the cause, and many waiting hours for the person having the problem (in this case, @gentauro) before they know what the issue is. While actually the problem could have been solved *immediately*, if just this pull request here were merged.

There is no reason to wait with merging this for a new release of Elm. As soon as this PR is merged, it will have beneficial effects. In this case, @gentauro would have been told immediately, by `BuildFromSource.hs`, that his `sudo runhaskell` is giving him a wrong GHC version.

If you need evidence that the pull request is strictly an improvement, not breaking anything, please have a look at the [Travis log](https://travis-ci.org/elm-lang/elm-platform/jobs/104031965). You can see that it is a log of the revised `BuildFromSource.hs` by looking at the [lines](https://travis-ci.org/elm-lang/elm-platform/jobs/104031965#L2680) containing:
```
Using GHC version 7.10.
Using cabal version 1.22.6.0.
```
which is not something that the current `BuildFromSource.hs` outputs (or checks).

**Comment by rtfeldman** [comment]
I understand the frustration, but I don't know Haskell well enough to review this, and @evancz has a ton on his plate right now. Wish I could be more help. :disappointed:

**Comment by jvoigtlaender** [comment]
> I understand the frustration, but I don't know Haskell well enough to review this, and @evancz has a ton on his plate right now.

The solution is to trust more people more. Not everything *needs* to be on his plate.

As far as this specific pull request is concerned, the Haskell does not really need additional review. Note that most of the work is in the first commit, which is not by me. Actually, I *have reviewed* (not implemented) that, then added a few improvements. Those improvements in the remaining commits are mostly trivial things and refactorings that don't need any deep Haskell knowledge. 

What qualifies me for reviewing that initial-and-most-comprehensive-change commit in the first place? Well, I probably know the current `BuildFromSource.hs` better than anybody else. Look at the commit history of that file. Consider who has been helping out people on the mailing list or in issues on Github throughout the last half year (and thus knows what the pain points are, and how much the automated check put forward here will help).

**Comment by jvoigtlaender** [comment]
Just a reminder (@evancz) that I strongly believe this should be merged *before* 0.17 is added to the build script.

**Comment by jvoigtlaender** [comment]
Merged current master and incorporated GHC version check into 0.17 section as well.

**Comment by jvoigtlaender** [comment]
The one AppVeyor failure here is not the PR's fault. See [here](https://ci.appveyor.com/project/rtfeldman/elm-platform/build/1.0.254/job/86l7hsl69utvcu1k). All other CI checks go through.

**Comment by jvoigtlaender** [comment]
Updated for the `0.17.1` route.

But @evancz, maybe you want to simply close this. I feel kind of stupid playing catch-up here without any indication you are even in favour of having this feature at all. Maybe you are not. Then you can close it, and also https://github.com/elm-lang/elm-platform/pull/118.

**Comment by jvoigtlaender** [comment]
@evancz, any chance you can consider this pull request? The discussion about building the platform from source, and which GHC is needed, currently on the mailing list and here on GitHub, and even just having to ask the user which version of GHC they did try to work with (a question which would not be necessary if this PR were merged, because then `BuildFromSource.hs` would spit out this information in the log script, so it would have been there to see without asking), ... make me wish again that there were some progress here.

**Comment by jvoigtlaender** [comment]
It makes me unreasonably happy that this PR was merged. :smile:

Thanks!

**Comment by evancz** [comment]
Seems like the fastest way to resolve the 8.0 stuff.

Take a look at the changes I made though. Preferring to avoid dependencies whenever possible. Always have type annotations. Do not use the "pattern match in multiple definitions" style. When you have tuples in tuples, decide to have some other thing instead. Lots of stuff like that would make it easier to sort out PRs like this.

**Pull request merged**
