### PR TITLE
Add npm installer

### PR DESCRIPTION
**Pull request by rtfeldman**
Still todo:
- [ ] Once merged, configure this to deploy only on `master`
- [x] Rename the binaries to agree with the `npm install -g elm` naming conventions
- [x] Build and upload the non-npm installers as well

### CODE REVIEW

**Comment by evancz** [comment]
I suspect there's some other weird stuff going on here.

The latest master branch should not work with GHC 7.8. I have removed some newly unnecessary imports that are definitely necessary in 7.8.

Check out [the travis thing from the compiler](https://github.com/elm-lang/elm-compiler/blob/master/.travis.yml). It uses [that hvr endpoint](https://github.com/elm-lang/elm-compiler/blob/master/.travis.yml#L6) I linked you the other day ([here](https://launchpad.net/~hvr/+archive/ubuntu/ghc)) that makes it pretty easy to get 7.10.

From there, I think just grabbing `bin/` directly is not so good. Dependencies of our code also create binaries, so there are usually two unrelated binaries in the bin directory when I go grab stuff. I forget their names, but just tarring up the whole thing will get non-elm binaries.

**Comment by rtfeldman** [comment]
Cool - I changed it to grab `bin/elm*` - does that seem reasonable, or would it be better to enumerate them?

**Comment by evancz** [comment]
Grabbing `elm*` will get everything. Seems like it'll be more reliable for the foreseeable future.

**Comment by jvoigtlaender** [comment]
@rtfeldman, what about the README? See https://github.com/rtfeldman/elm-bin/issues/2.

**Comment by jvoigtlaender** [comment]
... the point being that by having an essentially empty README and publishing from this branch to the main npm site, you have eliminated helpful information that was peviously given on https://www.npmjs.com/package/elm.

**Comment by rtfeldman** [comment]
Good point @jvoigtlaender - thoughts on this? https://github.com/elm-lang/elm-platform/commit/4dcdf084a97256385fefa962d65dbde7b340c4a7

**Comment by jvoigtlaender** [comment]
Yeah, this looks good. I'd also add the link to the http://elm-lang.org/Get-Started.elm page (no surprise, since I added it to the original `elm-bin` repo). The reason is that often we get questions on the mailing list or in repo issues about the next steps after installation. (What is the role of the differen binaries installed? How to set up a new project, etc.)

The http://elm-lang.org/Get-Started.elm page (the first half of it) exists to address such questions. Also, that page is pointed to, at the end of the installation processes, by both the Windows and the OS X installers. So it makes sense to also point it out to people who use the npm installer.

**Comment by rtfeldman** [comment]
:+1: added in b54a7dffac57ef0cc8bc9606f00cb9be9654227b - anything else that should go in there?

**Comment by jvoigtlaender** [comment]
Looks fine to me. Though for the moment I would really use the link http://elm-lang.org/Get-Started.elm I gave, not the link http://elm-lang.org/get-started you included. The former currently redirects to the latter, but who knows whether some reorganization takes place at some point where http://elm-lang.org/Get-Started.elm is still used but redirects to something else (that is then considered to be the "right" entry point). As a matter of fact, last time I looked, the Windows and OS X installers still used http://elm-lang.org/Get-Started.elm.

**Comment by evancz** [comment]
Great work! :D

It's kind of cool to see `BuildFromSource.hs` bundled with npm too :P

Anyway, thanks for getting all this together, this is very exciting!

**Pull request merged**
