### PR TITLE
request 2.72.0 had security vulnerability

### PR DESCRIPTION
**Pull request by gilesbowkett**
I upgraded this in my `package.json` from `request` 2.72.0 to 2.74.0, because 2.72.0 had a security vulnerability through its dependency `tough-cookie`.

Got this output on install initially:

```
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
```

Latest `request` is on `tough-cookie` 2.3.1, so upgrading `request` fixed this. _However_ - I'm installing Elm so I can build a Hello World, and afaict there aren't any tests for the installers, so I can't actually say I've tested this change. Seems harmless enough, but just for the record.

### CODE REVIEW

**Comment by louy2** [comment]
Makes me wonder where is `request` used. I suppose it would not be in the compiled JavaScript.

**Comment by gilesbowkett** [comment]
looks like it's used in the installer itself:

https://github.com/elm-lang/elm-platform/blob/master/installers/npm/install.js#L5

**Comment by gknapp** [comment]
Seeing this in elm 17.1 npm install (Linux Mint 17.3, nodejs 4.6 installed from nodesource, npm 2.15.9):

```bash
➜  ~ sudo npm install -g elm
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
/usr/bin/elm -> /usr/lib/node_modules/elm/binwrappers/elm
/usr/bin/elm-make -> /usr/lib/node_modules/elm/binwrappers/elm-make
/usr/bin/elm-package -> /usr/lib/node_modules/elm/binwrappers/elm-package
/usr/bin/elm-reactor -> /usr/lib/node_modules/elm/binwrappers/elm-reactor
/usr/bin/elm-repl -> /usr/lib/node_modules/elm/binwrappers/elm-repl

> elm@0.17.1 install /usr/lib/node_modules/elm
> node install.js

Downloading Elm binaries from https://dl.bintray.com/elmlang/elm-platform/0.17.1/linux-x64.tar.gz
```

**Comment by rtfeldman** [comment]
Seems reasonable, thanks!

**Pull request merged**
