### PR TITLE
add info about embedding/fullscreen changes

### PR DESCRIPTION
**Pull request by eeue56**
## Problem:

- No info about how to quickly upgrade embedding/fullscreen of elm apps

## Solution

- Add that info

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
The sentence following that table does not anymore seem to apply after your edition to the table.

**Comment by eeue56** [comment]
Well, these changes are mostly automatable. There aren't a huge amount of people using Elm through workers alone. But I agree, maybe there's no need for the following sentence?

**Comment by eeue56** [comment]
ping @evancz

**Comment by Warry** [comment]
worker is not removed, we are using it for a script that we updated this morning.

**Comment by eeue56** [comment]
It was when I made this ;)

On Wednesday, May 11, 2016, Maxime Dantec <notifications@github.com> wrote:

> worker is not removed, we are using it for a script that we updated this
> morning.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/elm-lang/elm-platform/pull/138#issuecomment-218493794>
>


-- 
Cheers,
Noah

noah@astraldynamics.co.uk
Astral Dynamics Cyf
Festri Cefn Y Waen, Deiniolen, Caernarfon, Gwynedd LL55 3NB
Company number 07726862
Registered in England and Wales

**Comment by evancz** [comment]
Makes sense, thanks @eeue56!

**Pull request merged**
