### PR TITLE
Check versions of cabal & ghc during build process

### PR DESCRIPTION
**Pull request by coventry**
This halts the build process if the ghc or cabal versions it's using are insufficient.

This is the first time I've written haskell, so I expect there is lots of room for improvement.  Critical feedback is welcome.

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
Thanks for doing this!

A couple of questions/comments:
* Are the modules you added as import all from packages that will definitely be installed with every (recent) GHC? If they depend on packages you only already happen to have previously, globally, installed on your machine, that would be a problem. Because we don't want to ship `BuildFromSource.hs` with a `.cabal` file or a list of dependencies people have to install first. Only standard packages should be used that will definitely be available even in a completely fresh GHC install.
* Can you make more explicit, in the `import` section, where newly used functions are coming from? For example, write `import Data.Version (makeVersion)`. Note that none of the previously existing import lines import anything unqualified without explicitly mentioning it. Best keep to that style.
* You are checking globally that people will have at least `minGHCVersion`, no matter which version of Elm they are trying to build. This might be harmful. For example, people trying to install Elm 0.15 will be told that they can't if they have GHC 7.8. Which is not true. And even more problematic, some of the old Elm versions might *only* be buildable with GHC 7.8 or earlier. So insisting on 7.10 to be used for all Elm versions would essentially exclude some older versions from ever be built again. Same problem going forward. Maybe Elm 0.18 will depend on GHC 8.0 but we still want people to be able to build Elm 0.17 with GHC 7.10 (maybe it won't even build with GHC 8.0 for some reason). Okay, all this is just a convoluted way of saying: Probably `minGHCVersion` shouldn't be a global constant, but instead a field that is added to each entry in the `configs` data structure.

**Comment by coventry** [comment]
> Are the modules you added as import all from packages that will definitely be installed with every (recent) GHC?

Is the CI implicitly testing this for a current set of GHC/cabal versions by building everything from scratch?  I don't know how to answer this definitively.  It still runs if I call `ghc-pkg-reset` beforehand.

**Comment by jvoigtlaender** [comment]
If there's CI running somewhere that exercises `BuildFromSource.hs` regularly, then yes, it should catch this. There isn't such CI running, and least not visibly, for this repository.

But: I just checked by hand whether all your new imports are from packages coming with GHC. Yes, they are. (Checking was by: look up the modules at https://www.haskell.org/hoogle/, then check whether the relevant packages are included in https://downloads.haskell.org/~ghc/latest/docs/html/libraries/index.html.)

**Comment by jvoigtlaender** [comment]
My statement about CI not currently running for this repo was nonsense, it appears.

**Comment by jvoigtlaender** [comment]
@coventry, do you want to complete this pull request? Alternatively, I could try to work on it to address the second and third point from my comment above.

**Comment by coventry** [comment]
Yep, I'll deal with it.  Thanks for asking.

**Comment by jvoigtlaender** [comment]
@coventry, are you still planning to complete this yourself?

**Comment by jvoigtlaender** [comment]
I completed this pull request. But since the changes are not getting merged over at the https://github.com/coventry/elm-platform repository, I'll open a separate, complete pull request here.

**Pull request merged**
