### PR TITLE
Runs elm-reactor inside a Docker container

### PR DESCRIPTION
**Pull request by Morendil**
Streamline installation for people using Docker.

### CODE REVIEW

**Comment by evancz** [comment]
I have not used docker before, can you tell me more about the responsibilities that come with this file? I'm not sure if I should be publishing it somehow, or if it comes with some maintenance burden that's best managed by the community rather than me.

**Comment by Morendil** [comment]
Basically, it's just like the "Build from Source" instructions, except executable and completely self-contained. You could use a Dockerfile as documentation; if you happen to run it on Docker you get a working install. (Docker itself is functionally similar to a virtual machine, one that can be configured by scripting. From a developer POV, it's a sandboxed, easily reproducible work environment.)

You'd need to keep the version numbers consistent with each other (or install a bundle which itself guarantees a consistent set of packages), if you wanted that install to always be up to date. You need to do that for the "Build from Source" instructions anyway. The DRY way would be to have your "Build from Source" section refer to the Dockerfile.

It would be a smart move IMO to periodically test install instructions by building from the Dockerfile, and publishing the file as an "official" build to Docker Registry. I believe Docker is going to get ever more popular as a way to test out new stuff in an isolated sandbox, without having to spend lots of time tweaking build instructions that "almost work" (i.e. don't work).

**Comment by evancz** [comment]
I think for the sake of maintainability, I don't want to take on this code. If we know a specific contributor who will keep it up to date, then I think it makes sense to do it independently at first. As that proves to be dependable, we can think about bringing it in here.

For now I want to keep the focus of the platform on automating the creation of installers.

**Comment by evancz** [comment]
That said, thank you for creating this, I think it still makes sense to share it around, perhaps on elm-discuss!

**Pull request closed without merging**
