### PR TITLE
Fix linix typo

### PR DESCRIPTION
**Pull request by cored**

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
I think that's not a typo. It's a deliberate mixture of the words linux and unix.

**Comment by evancz** [comment]
You give too much credit ;) I wasn't sure if I should say linux or unix there. Would one be more appropriate than the other? I never was 100% on what the *proper* name was for all the diversity of OSes in this family

**Comment by jvoigtlaender** [comment]
How about "if you are on some linux/unix OS"? :smile:

**Comment by evancz** [comment]
That seems good :) [This](http://unix.stackexchange.com/questions/4091/is-linux-a-unix) suggests that "linux" would cover all the tested cases I know of. I have no idea if our binaries work on FreeBSD. So I'm down to go with the current PR just to fix the initial typo.

**Pull request merged**
